/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-12-15 16:17:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userRegForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>DietHelper에 회원가입하세요.</title>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<!-- 부트스트랩 css 사용 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resource/css/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resource/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!--  회원가입(=로그인폼 수정) css 사용 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resource/css/login.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- DietHelper 홈페이지 아이콘 -->\r\n");
      out.write("<link href=\"/resource/assets/img/healthlogo.JPG\" rel=\"icon\">\r\n");
      out.write("\r\n");
      out.write("<!------ jquery   ---------->\r\n");
      out.write("<script src=\"/resources/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- 폰트 -->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Open+Sans:400,700\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<!-- 회원가입 창 왼쪽 상단 DietHelper 로고 네비게이션 바 -->\r\n");
      out.write("  <body class=\"align\">\r\n");
      out.write("\t<!-- Navigation-->\r\n");
      out.write("\t<nav class=\"navbar navbar-expand-lg navbar-light fixed-top\"\r\n");
      out.write("\t\tid=\"mainNav\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<a class=\"navbar-brand js-scroll-trigger\" href=\"/index.do\"\r\n");
      out.write("\t\t\t\tstyle=\"color: #778899;\">\r\n");
      out.write("\t\t\t\t<b>Diet \r\n");
      out.write("\t\t\t\t<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-activity\"><polyline points=\"22 12 18 12 15 21 9 3 6 12 2 12\"></polyline></svg>\r\n");
      out.write("\t\t\t\tHelper\r\n");
      out.write("\t\t\t</b></a>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\"\r\n");
      out.write("\t\t\t\t\t\thref=\"/Login.do\" style=\"color: #778899;\">Log In</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\"\r\n");
      out.write("\t\t\t\t\t\thref=\"/Login/UserRegForm.do\" style=\"color: #778899;\">Sign Up</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- 회원가입 화면 Diet Helper 글씨 -->\r\n");
      out.write("<div class=\"mx-auto text-center\">\r\n");
      out.write("\t\t<h1 class=\"mx-auto my-0 text-uppercase\">\r\n");
      out.write("\t\t\t<b>Diet</b>\r\n");
      out.write("\t\t\t<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-activity\"> <polyline points=\"22 12 18 12 15 21 9 3 6 12 2 12\"></polyline></svg>\r\n");
      out.write("\t\t</h1>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t\t<h1 class=\"mx-auto my-0 text-uppercase\">\r\n");
      out.write("\t\t\t<b>Helper</b>\r\n");
      out.write("\t\t\t</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 회원가입을 위한 회원정보 입력 폼(유효성 체크 자동) -->\r\n");
      out.write("\t<div class=\"grid\">\r\n");
      out.write("\r\n");
      out.write("\t\t<form action=\"/insertMember.do\" method=\"POST\" class=\"form login\"\r\n");
      out.write("\t\t\tonsubmit=\"return InsertCheck()\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"form__field\">\r\n");
      out.write("\t\t\t\t<label for=\"email\"><svg class=\"icon\"><use xmlns:xlink=\"http://www.w3.org/1999/xlink\" xlink:href=\"#user\"></use></svg><span class=\"hidden\"></span></label> \r\n");
      out.write("\t\t\t\t<input id=\"email\" type=\"email\" name=\"email\" class=\"form__input\" placeholder=\"이메일을 입력하세요\" style=\"padding: 0px 0px 0px 12px; color: black;\" onfocusout=\"EmailChk()\" autocomplete=\"off\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"form__field\">\r\n");
      out.write("\t\t\t\t<label for=\"username\"><svg class=\"icon\"><use xmlns:xlink=\"http://www.w3.org/1999/xlink\" xlink:href=\"#user\"></use></svg><span class=\"hidden\"></span></label> \r\n");
      out.write("\t\t\t\t<input id=\"name\" type=\"text\" name=\"user_name\" size=\"6\" class=\"form__input\" placeholder=\"&nbsp;이름을 입력하세요\" autocomplete=\"off\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"form__field\">\r\n");
      out.write("\t\t\t\t<label for=\"login__password\"><svg class=\"icon\"><use xmlns:xlink=\"http://www.w3.org/1999/xlink\" xlink:href=\"#lock\"></use></svg><span class=\"hidden\">Password</span></label> \r\n");
      out.write("\t\t\t\t<input id=\"password_1\" type=\"password\" name=\"password\" size=\"15\" class=\"form__input\" placeholder=\"&nbsp; 영문, 숫자, 특수문자 포함 비밀번호\" >\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div  class=\"alert alert-danger\" id=\"alert-check\">영문,숫자,특수문자를 포함한 12~20자로 설정해주세요.</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"form__field\">\r\n");
      out.write("\t\t\t\t<label for=\"login__password1\"><svg class=\"icon\"> <use xmlns:xlink=\"http://www.w3.org/1999/xlink\" xlink:href=\"#lock\"></use></svg><span class=\"hidden\">Password</span></label> \r\n");
      out.write("\t\t\t\t<input id=\"password_2\"\r\n");
      out.write("\t\t\t\t\ttype=\"password\" name=\"password2\" size=\"15\" class=\"form__input\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"&nbsp;비밀번호 확인을 입력하세요\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 비밀번호 입력 시 자동으로 비밀번호와 확인 부분이 일치하는지 alert -->\r\n");
      out.write("\t\t\t<div class=\"alert alert-success\" id=\"alert-success\">비밀번호가\r\n");
      out.write("\t\t\t\t일치합니다.</div>\r\n");
      out.write("\t\t\t<div class=\"alert alert-danger\" id=\"alert-danger\">비밀번호가 일치하지\r\n");
      out.write("\t\t\t\t않습니다.</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"form__field\">\r\n");
      out.write("\t\t\t\t<label for=\"login__password1\"><svg class=\"icon\"><use xmlns:xlink=\"http://www.w3.org/1999/xlink\" xlink:href=\"#user\"></use></svg><span class=\"hidden\"></span></label> \r\n");
      out.write("\t\t\t\t<input id=\"login__password\" type=\"text\" name=\"user_an\" class=\"form__input\" placeholder=\"&nbsp;닉네임을 입력하세요\" autocomplete=\"off\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"form__field\"> \r\n");
      out.write("\t\t\t\t <input type=\"text\" id=\"sample2_postcode\" placeholder=\"우편번호\" autocomplete=\"off\">\r\n");
      out.write("\t\t\t\t <input type=\"button\" onclick=\"sample2_execDaumPostcode()\" value=\"우편번호 찾기\" class=\"btn btn-primary disabled\" required=\"required\" style=\"width:125px;margin:0px 0px 0px 0px;\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"form__field\">\r\n");
      out.write("                 <input type=\"text\" class=\"form-control form-control-user\" name=\"addr\" id=\"addr\" placeholder=\"주소를 등록해 주세요.\" required=\"required\" autocomplete=\"off\" style=\"color:white;border-width: 0 0;\">\r\n");
      out.write("            </div> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 입력 완료 후 분홍색 회원가입 버튼을 눌러 유효성 체크에 이상 없을 시, 회원가입 -->\r\n");
      out.write("\t\t\t<div class=\"form__field\">\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"회원가입\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t<p class=\"text--center\">\r\n");
      out.write("\t\t\t&nbsp;&nbsp;이미 DietHelper 회원이신가요? <a href=\"/Login.do\">&nbsp;로그인</a>\r\n");
      out.write("\t\t\t<svg class=\"icon\"><use xmlns:xlink=\"http://www.w3.org/1999/xlink\" xlink:href=\"assets/images/icons.svg#arrow-right\"></use></svg>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 이메일, 비밀번호 입력할 때 입력란 옆에 사용되는 아이콘 -->\r\n");
      out.write("\t  <svg xmlns=\"http://www.w3.org/2000/svg\" class=\"icons\"><symbol id=\"arrow-right\" viewBox=\"0 0 1792 1792\"><path d=\"M1600 960q0 54-37 91l-651 651q-39 37-91 37-51 0-90-37l-75-75q-38-38-38-91t38-91l293-293H245q-52 0-84.5-37.5T128 1024V896q0-53 32.5-90.5T245 768h704L656 474q-38-36-38-90t38-90l75-75q38-38 90-38 53 0 91 38l651 651q37 35 37 90z\"/></symbol><symbol id=\"lock\" viewBox=\"0 0 1792 1792\"><path d=\"M640 768h512V576q0-106-75-181t-181-75-181 75-75 181v192zm832 96v576q0 40-28 68t-68 28H416q-40 0-68-28t-28-68V864q0-40 28-68t68-28h32V576q0-184 132-316t316-132 316 132 132 316v192h32q40 0 68 28t28 68z\"/></symbol><symbol id=\"user\" viewBox=\"0 0 1792 1792\"><path d=\"M1600 1405q0 120-73 189.5t-194 69.5H459q-121 0-194-69.5T192 1405q0-53 3.5-103.5t14-109T236 1084t43-97.5 62-81 85.5-53.5T538 832q9 0 42 21.5t74.5 48 108 48T896 971t133.5-21.5 108-48 74.5-48 42-21.5q61 0 111.5 20t85.5 53.5 62 81 43 97.5 26.5 108.5 14 109 3.5 103.5zm-320-893q0 159-112.5 271.5T896 896 624.5 783.5 512 512t112.5-271.5T896 128t271.5 112.5T1280 512z\"/></symbol></svg>\r\n");
      out.write("\r\n");
      out.write("<!-- 회원가입 유효성 체크를 위한 UserRegForm js 사용 -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/resources/js/UserRegForm.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- 부트스트랩 js 사용 -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/resource/js/bootstrap.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/resource/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write(" <!--  다음 주소 API -->\r\n");
      out.write("   <script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("   \r\n");
      out.write("   <div id=\"layer\"\r\n");
      out.write("      style=\"display: none; position: fixed; overflow: hidden; z-index: 1; -webkit-overflow-scrolling: touch;\">\r\n");
      out.write("     \r\n");
      out.write("      <img src=\"//t1.daumcdn.net/postcode/resource/images/close.png\"\r\n");
      out.write("         id=\"btnCloseLayer\"\r\n");
      out.write("         style=\"cursor: pointer; position: absolute; right: -3px; top: -3px; z-index: 1\"\r\n");
      out.write("         onclick=\"closeDaumPostcode()\" alt=\"닫기 버튼\">\r\n");
      out.write("         \r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   <script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/resources/js/daumAPI.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
